export const sagaActions = {
  CAMBIO_DETALLE_SAGA: 'CAMBIO_DETALLE_SAGA',
  ADD_CHECKS_SAGA: 'ADD_CHECKS_SAGA',
  REMOVE_CHECKS_SAGA: 'REMOVE_CHECKS_SAGA',
  REMOVE_ALL_CHECKS_SAGA: 'REMOVE_ALL_CHECKS_SAGA',
  CHANGE_LOGIN_STATE_SAGA: 'CHANGE_LOGIN_STATE_SAGA',
  SET_LOGIN_DATA_USER: 'SET_LOGIN_DATA_USER'
}